---
extends:
  - stylelint-config-standard
rules:
  at-rule-no-deprecated:
    - true
    - ignoreAtRules:
        - apply
  at-rule-no-unknown:
    - true
    - ignoreAtRules:
        - config
  media-feature-name-no-unknown:
    - true
    - ignoreMediaFeatureNames:
        - screen
  unit-no-unknown:
    - true
    - ignoreUnits:
        - xl

  declaration-block-no-redundant-longhand-properties:

  no-duplicate-selectors:

  media-query-no-invalid:
