---
extends:
  - stylelint-config-standard
rules:
  at-rule-no-unknown:
    - true
    - ignoreAtRules:
        - tailwind
        - apply
  unit-no-unknown:
    - true
    - ignoreUnits:
        - xl
  function-no-unknown:
    - true
    - ignoreFunctions:
        - theme

  no-duplicate-selectors:
