title: About:Me
avatar: https://avatars.githubusercontent.com/ms-jpq
description: >-
  a showcase for my personal projects

url: "https://ms-jpq.github.io/"
baseurl: ""

email: github@bigly.dog
twitter_username: "TODO - REMOVE THIS"
github_username: ms-jpq

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
