---
user: ms-jpq

header:
  title: Creative Portfolio
  menu: Menu

aside:
  about_me:
    title: Creative Portfolio
    desc:
      - >-
        I am a polyglot programmer and software engineer with more than 5 years
        of experience.
      - >-
        Professional interests: functional design, metaprogramming.

  nav:
    - title: PLACE_HOLDER_NAV_1
      link: about:blank
    - title: PLACE_HOLDER_NAV_2
      link: about:blank
    - title: PLACE_HOLDER_NAV_3
      link: about:blank

  contacts:
    email: github@bigly.dog
    github: ms-jpq

footer:
  desc:
    - >-
      © 2020 ms-jpq
