---
user: ms-jpq

repo_shim: /r/

header:
  title: Creative Portfolio
  menu: Menu

aside:
  nav:
    - title: home
      link: ""
    - title: about
      link: about-me
    - title: get in touch
      link: contact

  contacts:
    email: github@bigly.dog
    linkedin: ""
    github: ms-jpq
    dockerhub: msjpq
    stackoverflow: 15744711
