[project]
name            = "p"
readme          = "README.md"
requires-python = ">=3.11"
version         = "0"

dependencies = [
  "std2@https://github.com/ms-jpq/std2/archive/1fbd11fb4854a38176bc7377b4ef9f409f400bcf.tar.gz",
  "Jinja2",
  "Markdown",
  "PyYAML",
  "Pygments",
]
[project.optional-dependencies]
dev = ["mypy", "types-PyYAML", "types-Markdown", "black", "isort"]
