[project]
name            = "p"
readme          = "README.md"
requires-python = ">=3.11"
version         = "0"

dependencies = [
  "std2@https://github.com/ms-jpq/std2/archive/b733ecb989ac78d65c6855c32000d88c58f69b09.tar.gz",
  "Jinja2",
  "Markdown",
  "PyYAML",
  "Pygments",
]
[project.optional-dependencies]
dev = ["mypy", "types-PyYAML", "types-Markdown", "black", "isort"]
