---
name: CI

on:
  push:
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Apt
        run: sudo apt install --yes -- libwebp-dev

      - name: Pip Packages
        run: pip install -U mypy types-PyYAML types-Markdown

      - name: Pip Packages 2
        run: pip install -U -r requirements.txt

      - name: Npm Packages
        run: npm install

      - name: Lint
        run: mypy -- .

      - name: Build
        run: python3 -m src --production -- 'ms-jpq' 'dist'
