---
on:
  push:
    branches-ignore:
      - show

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4

      - run: |-
          make lint

      - run: |-
          make build
