---
name: Build

on:
  push:
    branches:
      - show
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4

      - run: |-
          make lint

      - env:
          CI_TOKEN: ${{ secrets.CI_TOKEN }}
        run: |-
          make ci
